name: PR Checks

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  pr_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Run tests
        run: npm run test

      - name: Lint project
        run: npm run lint

      - name: Build project
        run: npm run build 